#ifndef PROMPT_TEMPLATES_H
#define PROMPT_TEMPLATES_H

#include <string>
#include <map>

class PromptTemplates {
public:
    // System prompts for different documentation contexts
    static std::string getSystemPrompt(const std::string& doc_type) {
        static const std::map<std::string, std::string> system_prompts = {
            {"api_documentation",
             "You are an expert API technical writer following OpenAPI/Swagger and industry-standard REST API documentation best practices. "
             "Create comprehensive, developer-friendly API documentation using the modern API documentation structure. "
             "Follow the pattern: Overview → Authentication → Rate Limiting → Endpoints (grouped by resource) → Error Handling → Examples → SDKs. "
             "For each endpoint, use this exact structure: METHOD /path, Description, Request (headers, params, body schema), "
             "Response (status codes, body schema), and Complete Example (with curl). Use tables for parameters. "
             "Include response codes: 200, 201, 400, 401, 403, 404, 429, 500. Write in present tense, active voice. "
             "Use consistent terminology. Format all code examples with proper syntax highlighting markers. "
             "Include versioning information if detected. Structure response/request schemas clearly with types and constraints."},

            {"database_documentation",
             "You are a database architect creating comprehensive database documentation following modern data modeling practices. "
             "Structure documentation as: Overview → ERD Description → Tables (detailed) → Relationships → Indexes → Migrations → Query Patterns → Performance. "
             "For each table, provide: Purpose, Schema (column name, type, constraints, default, description), Primary Key, Foreign Keys, Indexes, Sample Data. "
             "Use tables for schema presentation. Describe relationships with cardinality (1:1, 1:N, N:M). "
             "Include index rationale and query optimization notes. Document any triggers, stored procedures, or views. "
             "Explain normalization decisions. Provide example queries for common operations. "
             "Use mermaid-style ERD descriptions. Include migration history if available. Be precise with data types and constraints."},

            {"architecture_documentation",
             "You are a senior software architect creating Arc42-inspired architecture documentation. "
             "Structure as: Executive Summary → Context & Scope → Solution Strategy → Building Blocks → Runtime View → "
             "Deployment View → Cross-cutting Concerns → Architecture Decisions → Quality Requirements → Risks & Technical Debt. "
             "For Building Blocks, use component diagrams descriptions with clear responsibilities. "
             "For Runtime View, describe key scenarios with sequence diagrams in text. For Architecture Decisions, use ADR format: "
             "Context, Decision, Consequences. Include Quality Attribute Scenarios (stimulus-response format). "
             "Describe patterns used (MVC, Repository, CQRS, etc.) and WHY they were chosen. "
             "Document technology stack with justification. Include scalability analysis. "
             "Explain security architecture in detail. Aim for 2500-3500 words with deep technical insight. "
             "Use diagrams descriptions with mermaid syntax. Be specific, not generic."},

            {"developer_onboarding",
             "You are a Developer Experience specialist creating a welcoming, comprehensive onboarding guide following the Diátaxis framework. "
             "Structure as: Welcome → Prerequisites → Quick Start (15-min goal) → Development Environment Setup → "
             "Architecture Overview → Code Organization → Development Workflow → First Contribution Guide → Resources. "
             "Make the Quick Start immediately actionable with copy-paste commands. Provide platform-specific instructions (macOS, Linux, Windows). "
             "Include a project walkthrough with file tree and key file explanations. Document git workflow (branching strategy, PR process). "
             "Provide IDE setup recommendations with extensions/plugins. Include debugging setup. "
             "Add a 'First Bug Fix' tutorial with step-by-step instructions. Link to coding standards. "
             "Include communication channels and team contacts. Add FAQ for common setup issues. "
             "Tone: friendly and encouraging. Assume smart but unfamiliar reader."},

            {"code_conventions",
             "You are a code quality expert creating enforceable coding standards documentation. "
             "Structure as: Philosophy → Language-Specific Standards → Naming Conventions → File Organization → "
             "Code Structure → Documentation Standards → Testing Requirements → Security Guidelines → Code Review Checklist. "
             "For each convention, provide: Rule, Rationale, Good Example, Bad Example. "
             "Include tool configurations (linters, formatters) with exact settings. Document naming patterns: "
             "camelCase, PascalCase, snake_case with context. Specify file naming patterns. "
             "Define function/method length limits, complexity limits, nesting depth. Document comment requirements. "
             "Include error handling patterns. Specify dependency management rules. Add git commit message format. "
             "Provide code review checklist with quality gates. Make conventions specific and measurable, not vague. "
             "Include examples from the actual codebase when possible."},

            {"user_manual",
             "You are a UX writer creating user-centered documentation following the Diátaxis 'How-To Guides' pattern. "
             "Structure as: Overview → Getting Started → Core Features (task-based) → Advanced Features → Settings → FAQ → Glossary. "
             "Write in 2nd person ('you'). Use task-based organization (not feature-based): 'How to create...' not 'The Create Feature'. "
             "For each task: Brief intro, Prerequisites, Step-by-step with numbered list, Expected result, Troubleshooting tips. "
             "Include screenshots callouts (e.g., '[Screenshot: Dashboard with Settings highlighted]'). "
             "Use short sentences (15-20 words max). Avoid jargon; explain technical terms when necessary. "
             "Add tips/notes/warnings with emoji markers or blockquotes. Include keyboard shortcuts. "
             "Provide common workflows as tutorials. Use tables for settings/options. "
             "Reading level: Grade 8-10. Be concise but complete. Focus on user goals, not system features."},

            {"installation_guide",
             "You are a DevOps technical writer creating comprehensive installation documentation. "
             "Structure as: Overview → System Requirements → Pre-Installation Checklist → Installation (by platform) → "
             "Configuration → Verification → Troubleshooting → Uninstallation. "
             "Provide exact requirements: OS versions, RAM, disk space, network ports, dependencies with versions. "
             "Give installation instructions for: macOS, Ubuntu/Debian, CentOS/RHEL, Windows, Docker. "
             "Use code blocks for all commands with copy button format. Include both manual and automated (script) installation. "
             "Document environment variables in table format with defaults. Provide post-install verification steps with expected output. "
             "Include common issues in troubleshooting with symptoms → diagnosis → solution format. "
             "Add upgrade/migration instructions. Specify security configurations. "
             "Include firewall rules, permissions, service management commands. Be explicit about PATH modifications. "
             "Provide both development and production installation variants."},

            {"faq",
             "You are a support documentation specialist creating a comprehensive FAQ following information architecture best practices. "
             "Structure as: Quick Answers (top 5) → Categorized FAQs → Still Need Help section. "
             "Categories: Getting Started, Installation & Setup, Usage, Troubleshooting, Integration, Performance, Security, Billing/Licensing. "
             "Format each Q&A as: **Q: [Question in user's language]** / A: [Concise answer with examples/links]. "
             "Start answers with direct response, then provide details. Keep answers under 150 words. "
             "Use bullet points for multi-step answers. Link to detailed docs for complex topics. "
             "Include code snippets for technical FAQs. Add 'See also' cross-references. "
             "Anticipate follow-up questions. Use common user vocabulary, not internal jargon. "
             "Structure questions as users would ask them (conversational). Include error message FAQs with full message text. "
             "Provide answers that solve problems, not just explain features."},

            {"troubleshooting_guide",
             "You are a technical support engineer creating a systematic troubleshooting guide. "
             "Structure as: Quick Diagnostics → Common Issues → Advanced Debugging → Error Reference → Getting Support. "
             "For each issue use: Issue Title → Symptoms (bullet list) → Possible Causes → Solutions (ordered by likelihood) → Prevention. "
             "Include diagnostic commands with expected vs. actual output examples. Organize by: Installation Issues, Runtime Errors, "
             "Performance Problems, Integration Issues, Data Issues, Security/Permission Issues. "
             "Create an Error Code Reference table: Code, Message, Meaning, Solution, Related Docs. "
             "Add a debugging flowchart in text/mermaid format. Include log file locations and what to look for. "
             "Provide system health check commands. Document known issues and workarounds. "
             "Include 'How to Report a Bug' section with template. Add escalation paths. "
             "Use clear, non-judgmental language. Assume user competence but not omniscience. "
             "Format solutions as numbered steps with verification after each step."},

            {"release_notes",
             "You are a release manager creating user-focused release notes following Keep a Changelog format. "
             "Structure as: [Version] - [Date] → Summary → Breaking Changes → New Features → Enhancements → Bug Fixes → "
             "Deprecated → Security → Upgrade Instructions → Known Issues. "
             "Use semantic versioning (MAJOR.MINOR.PATCH). Write in past tense. "
             "For breaking changes: What changed, Why, Migration path, Before/After examples. "
             "For features: What it does, Who benefits, How to use (link to docs), Screenshots/demos mention. "
             "For bugs: Issue ID, Description, Impact, Fixed behavior. Use issue tracker IDs when available. "
             "Highlight security fixes with severity (Critical, High, Medium, Low). "
             "Provide upgrade commands and rollback procedure. Document deprecated features with sunset timeline. "
             "Include contributor acknowledgments. Add download links/instructions. "
             "Write for users, not developers (impact-focused, not implementation-focused). Keep entries concise (1-3 sentences)."},

            {"integration_guide",
             "You are an integration architect creating comprehensive integration documentation. "
             "Structure as: Overview → Authentication & Authorization → Endpoints/APIs → SDKs & Libraries → "
             "Webhooks → Rate Limiting → Error Handling → Testing → Examples → Best Practices. "
             "Include integration architecture diagram description. Document auth flows with sequence diagrams. "
             "Provide SDK quick starts in multiple languages (Python, JavaScript, Java, etc.). "
             "Show complete, working code examples (not snippets). Include error handling in examples. "
             "Document webhook payload schemas and signature verification. Provide test credentials/sandbox environment info. "
             "Include rate limit details: requests/minute, burst limits, backoff strategies. "
             "Show common integration patterns: Polling, Webhooks, Batch processing. Document data mapping/transformation needs. "
             "Provide integration checklist. Include security best practices: credential storage, HTTPS requirements, token refresh. "
             "Add troubleshooting for common integration issues. Use OpenAPI/AsyncAPI specs if applicable."},

            {"technical_specification",
             "You are a technical specification writer creating detailed engineering specifications following IEEE 29148 principles. "
             "Structure as: System Overview → Stakeholders & Concerns → Functional Requirements → Non-Functional Requirements → "
             "System Architecture → Data Models → Interface Specifications → Security Requirements → Performance Requirements → "
             "Constraints & Assumptions → Acceptance Criteria. "
             "Use RFC 2119 keywords: MUST, SHOULD, MAY. Number all requirements (e.g., REQ-001). "
             "For functional requirements: ID, Description, Priority, Acceptance Criteria, Dependencies. "
             "For NFRs: Performance (latency, throughput), Scalability (concurrent users, data volume), "
             "Reliability (uptime, MTBF), Security (authentication, authorization, encryption), Maintainability. "
             "Include interface specifications: API contracts, message formats, protocols. Document data models with schema. "
             "Specify technology stack with version requirements. Include test strategy. "
             "Define success metrics and KPIs. Document external dependencies. Provide traceability matrix. "
             "Be precise, measurable, and testable. Avoid ambiguity. Use tables, diagrams, and formal notation where appropriate."}
        };

        auto it = system_prompts.find(doc_type);
        if (it != system_prompts.end()) {
            return it->second;
        }

        // Default system prompt
        return "You are a technical documentation expert. Create clear, comprehensive, "
               "and well-structured documentation in Markdown format.";
    }

    // Generate context-aware prompt with repository data
    static std::string buildPrompt(
        const std::string& doc_type,
        const std::string& audience,
        const std::string& repo_overview,
        const std::string& file_structure,
        const std::string& key_files_summary
    ) {
        std::ostringstream prompt;

        prompt << "# Documentation Generation Task\n\n";
        prompt << "**Documentation Type:** " << doc_type << "\n";
        prompt << "**Target Audience:** " << audience << "\n\n";

        prompt << "## Repository Overview\n\n";
        prompt << repo_overview << "\n\n";

        prompt << "## File Structure\n\n";
        prompt << file_structure << "\n\n";

        prompt << "## Key Files and Components\n\n";
        prompt << key_files_summary << "\n\n";

        prompt << "---\n\n";
        prompt << "Based on the above information, generate comprehensive "
               << doc_type << " documentation.\n\n";

        // Add specific instructions based on doc type
        prompt << getSpecificInstructions(doc_type, audience);

        return prompt.str();
    }

private:
    static std::string getSpecificInstructions(const std::string& doc_type, const std::string& audience) {
        static const std::map<std::string, std::string> instructions = {
            {"api_documentation",
             "## Documentation Structure:\n\n"
             "# API Documentation\n\n"
             "## Overview\n"
             "- Brief description of the API purpose and capabilities\n"
             "- Base URL(s) and versioning scheme\n"
             "- Supported formats (JSON, XML, etc.)\n\n"
             "## Authentication\n"
             "- Authentication method (API Key, OAuth2, JWT, etc.)\n"
             "- How to obtain credentials\n"
             "- How to include auth in requests (header, query param)\n"
             "- Example authentication request\n\n"
             "## Rate Limiting\n"
             "- Requests per minute/hour limits\n"
             "- Rate limit headers\n"
             "- Handling rate limit errors\n\n"
             "## Endpoints\n"
             "Group by resource (e.g., Users, Projects, Documents)\n\n"
             "For EACH endpoint:\n"
             "### METHOD /path/to/endpoint\n"
             "**Description:** What this endpoint does\n\n"
             "**Request:**\n"
             "- Headers: (table: Name, Type, Required, Description)\n"
             "- URL Parameters: (table)\n"
             "- Query Parameters: (table)\n"
             "- Request Body: (schema with types)\n\n"
             "**Response:**\n"
             "- Status Codes: 200, 201, 400, 401, 404, 500 (with meaning)\n"
             "- Response Body: (schema with example)\n\n"
             "**Example:**\n"
             "```bash\n"
             "curl -X METHOD URL \\\n"
             "  -H \"Authorization: Bearer TOKEN\" \\\n"
             "  -d '{\"key\": \"value\"}'\n"
             "```\n"
             "Response:\n"
             "```json\n"
             "{\"result\": \"success\"}\n"
             "```\n\n"
             "## Error Handling\n"
             "- Error response format\n"
             "- Common error codes and meanings\n\n"
             "## SDKs and Libraries\n"
             "- Available client libraries (if any)\n\n"},

            {"database_documentation",
             "## Documentation Structure:\n\n"
             "# Database Documentation\n\n"
             "## Overview\n"
             "- Database system used (PostgreSQL, MongoDB, etc.)\n"
             "- Database name and purpose\n"
             "- Key design decisions and principles\n\n"
             "## Entity Relationship Diagram\n"
             "```mermaid\n"
             "erDiagram\n"
             "  USER ||--o{ ORDER : places\n"
             "  ORDER ||--|{ LINE-ITEM : contains\n"
             "```\n"
             "Text description of relationships\n\n"
             "## Tables/Collections\n\n"
             "For EACH table:\n"
             "### table_name\n"
             "**Purpose:** What this table stores\n\n"
             "**Schema:**\n"
             "| Column | Type | Constraints | Default | Description |\n"
             "|--------|------|-------------|---------|-------------|\n"
             "| id | INT | PRIMARY KEY, AUTO_INCREMENT | - | Unique identifier |\n\n"
             "**Indexes:**\n"
             "- idx_name (column1, column2) - Purpose: improve query performance for...\n\n"
             "**Relationships:**\n"
             "- FOREIGN KEY (user_id) REFERENCES users(id) - 1:N relationship\n\n"
             "**Sample Data:**\n"
             "```sql\n"
             "INSERT INTO table_name VALUES (...);\n"
             "```\n\n"
             "## Common Queries\n"
             "```sql\n"
             "-- Get all users with orders\n"
             "SELECT ... FROM ...\n"
             "```\n\n"
             "## Migrations\n"
             "- Migration history and rationale\n\n"
             "## Performance Considerations\n"
             "- Query optimization notes\n"
             "- Index strategy\n\n"},

            {"architecture_documentation",
             "## Documentation Structure:\n\n"
             "# Architecture Documentation\n\n"
             "## Executive Summary\n"
             "- System purpose in 2-3 sentences\n"
             "- Key architectural characteristics (microservices, monolith, serverless, etc.)\n"
             "- Primary quality attributes (scalability, security, performance)\n\n"
             "## Context & Scope\n"
             "- What problem does this system solve?\n"
             "- System boundaries (what's in, what's out)\n"
             "- External interfaces and integrations\n"
             "- User personas and use cases\n\n"
             "## Solution Strategy\n"
             "- High-level approach to solving the problem\n"
             "- Key technology decisions\n"
             "- Top 3-5 architectural principles\n\n"
             "## Building Blocks View\n"
             "```mermaid\n"
             "graph TD\n"
             "  A[Frontend] --> B[API Gateway]\n"
             "  B --> C[Service 1]\n"
             "```\n\n"
             "For EACH major component:\n"
             "### Component Name\n"
             "- **Responsibility:** What it does\n"
             "- **Technology:** Languages, frameworks\n"
             "- **Key Classes/Modules:** Main code units\n"
             "- **Dependencies:** What it depends on\n"
             "- **Interfaces:** How others interact with it\n\n"
             "## Runtime View\n"
             "Key scenarios:\n"
             "### Scenario: User Authentication\n"
             "```mermaid\n"
             "sequenceDiagram\n"
             "  User->>Frontend: Login\n"
             "  Frontend->>API: POST /auth\n"
             "```\n"
             "1. User submits credentials\n"
             "2. Frontend validates and sends to API\n"
             "3. ...\n\n"
             "## Deployment View\n"
             "- Infrastructure: Cloud provider, containers, orchestration\n"
             "- Environment architecture (dev, staging, prod)\n"
             "- CI/CD pipeline\n"
             "- Deployment strategy (blue-green, rolling, etc.)\n\n"
             "## Cross-cutting Concerns\n"
             "### Security\n"
             "- Authentication & Authorization approach\n"
             "- Data encryption (at rest, in transit)\n"
             "- Security patterns implemented\n\n"
             "### Observability\n"
             "- Logging strategy\n"
             "- Monitoring and metrics\n"
             "- Distributed tracing\n\n"
             "### Error Handling\n"
             "- Error propagation strategy\n"
             "- Retry and fallback patterns\n\n"
             "## Architecture Decisions (ADRs)\n"
             "For EACH major decision:\n"
             "### ADR-001: [Decision Title]\n"
             "**Status:** Accepted | Proposed | Deprecated\n"
             "**Context:** What problem are we solving? What constraints exist?\n"
             "**Decision:** What did we decide? Be specific.\n"
             "**Consequences:** Positive and negative outcomes. Trade-offs.\n"
             "**Alternatives Considered:** What else did we evaluate?\n\n"
             "## Quality Requirements\n"
             "- **Performance:** Expected latency (p50, p95, p99), throughput\n"
             "- **Scalability:** Concurrent users, data volume, growth projections\n"
             "- **Availability:** Uptime SLA, MTBF, MTTR\n"
             "- **Security:** Compliance requirements, threat model\n"
             "- **Maintainability:** Code complexity, test coverage\n\n"
             "## Risks & Technical Debt\n"
             "- Known limitations\n"
             "- Technical debt items with priority\n"
             "- Mitigation strategies\n\n"},

            {"developer_onboarding",
             "## Documentation Structure:\n\n"
             "# Developer Onboarding Guide\n\n"
             "## Welcome!\n"
             "Welcome to [Project Name]! This guide will help you get started as a contributor.\n\n"
             "## Prerequisites\n"
             "Before you begin, ensure you have:\n"
             "- [ ] Tool 1 (version X.X+)\n"
             "- [ ] Tool 2\n"
             "- [ ] Account access: GitHub, CI/CD, etc.\n"
             "- [ ] Knowledge: Language basics, framework familiarity\n\n"
             "## Quick Start (15 minutes)\n"
             "Get the project running:\n"
             "```bash\n"
             "# 1. Clone\n"
             "git clone ...\n"
             "# 2. Install\n"
             "...\n"
             "# 3. Run\n"
             "...\n"
             "```\n"
             "You should see: [expected output]\n\n"
             "## Development Environment Setup\n"
             "### macOS\n"
             "```bash\n"
             "brew install ...\n"
             "```\n"
             "### Linux (Ubuntu/Debian)\n"
             "```bash\n"
             "apt-get install ...\n"
             "```\n"
             "### Windows\n"
             "```powershell\n"
             "choco install ...\n"
             "```\n\n"
             "## Project Structure\n"
             "```\n"
             "project/\n"
             "├── src/          # Source code\n"
             "│   ├── api/      # API endpoints\n"
             "│   └── models/   # Data models\n"
             "├── tests/        # Test suite\n"
             "└── docs/         # Documentation\n"
             "```\n"
             "**Key Files:**\n"
             "- `src/main.js` - Application entry point\n"
             "- `config/` - Configuration files\n\n"
             "## Architecture Overview\n"
             "High-level system design:\n"
             "[Brief architecture explanation]\n\n"
             "## Development Workflow\n"
             "1. **Branching:** `git checkout -b feature/your-feature`\n"
             "2. **Coding:** Follow our [Code Conventions](link)\n"
             "3. **Testing:** `npm test` must pass\n"
             "4. **Committing:** Use format: `type(scope): description`\n"
             "5. **Pull Request:** Fill out PR template, request reviews\n"
             "6. **Merge:** Squash and merge after approval\n\n"
             "## IDE Setup\n"
             "**VS Code (Recommended):**\n"
             "- Extensions: ESLint, Prettier, ...\n"
             "- Settings: Copy `.vscode/settings.json`\n\n"
             "## First Contribution: Fix a Bug\n"
             "Let's fix issue #123 together:\n"
             "1. Read the issue description\n"
             "2. Reproduce the bug\n"
             "3. Locate the code\n"
             "4. Implement the fix\n"
             "5. Add a test\n"
             "6. Submit PR\n\n"
             "## Resources\n"
             "- [Architecture Docs](link)\n"
             "- [API Reference](link)\n"
             "- [Code Conventions](link)\n"
             "- Slack: #engineering\n"
             "- Team Lead: @username\n\n"
             "## FAQ\n"
             "**Q: Tests are failing locally?**\n"
             "A: Try...\n\n"},

            {"user_manual",
             "## Documentation Structure:\n\n"
             "# User Manual\n\n"
             "## Overview\n"
             "Brief description of what the software does and who it's for.\n\n"
             "## Getting Started\n"
             "### Your First Task\n"
             "Let's complete a basic task together:\n"
             "1. Step one with clear action\n"
             "2. Step two\n"
             "3. Result: You should see...\n\n"
             "## Core Features\n"
             "Organize by user tasks, not features:\n\n"
             "### How to [Task Name]\n"
             "**What you'll accomplish:** [Goal]\n"
             "**Prerequisites:** [What's needed]\n\n"
             "**Steps:**\n"
             "1. Navigate to...\n"
             "2. Click...\n"
             "3. Enter...\n\n"
             "[Screenshot: Dashboard showing X]\n\n"
             "**Expected Result:** [What should happen]\n\n"
             "**Troubleshooting:**\n"
             "- If you see error X: Try...\n\n"
             "**Tips:**\n"
             "> Keyboard shortcut: Cmd+K\n\n"
             "## Advanced Features\n"
             "For power users:\n\n"
             "## Settings & Configuration\n"
             "| Setting | Description | Default | Options |\n"
             "|---------|-------------|---------|----------|\n\n"
             "## Common Workflows\n"
             "### Workflow: [Name]\n"
             "Complete multi-step tutorial\n\n"
             "## FAQ\n"
             "Quick answers to common questions\n\n"
             "## Glossary\n"
             "- **Term:** Definition in simple language\n\n"},

            {"installation_guide",
             "## Documentation Structure:\n\n"
             "# Installation Guide\n\n"
             "## Overview\n"
             "What you're about to install and expected time: ~20 minutes\n\n"
             "## System Requirements\n"
             "### Minimum\n"
             "- OS: Ubuntu 20.04+, macOS 11+, Windows 10+\n"
             "- RAM: 4GB\n"
             "- Disk: 10GB free space\n"
             "- Network: Ports 80, 443, 8080 open\n\n"
             "### Recommended\n"
             "- RAM: 8GB\n"
             "- SSD storage\n\n"
             "### Dependencies\n"
             "- Node.js 18.x\n"
             "- PostgreSQL 14+\n"
             "- Docker 20.10+ (optional)\n\n"
             "## Pre-Installation Checklist\n"
             "- [ ] Verify system meets requirements\n"
             "- [ ] Backup existing data\n"
             "- [ ] Download installation package\n"
             "- [ ] Review security considerations\n\n"
             "## Installation\n\n"
             "### Option 1: Docker (Recommended)\n"
             "```bash\n"
             "docker pull ...\n"
             "docker run ...\n"
             "```\n\n"
             "### Option 2: macOS\n"
             "```bash\n"
             "# 1. Install dependencies\n"
             "brew install ...\n"
             "# 2. Download and install\n"
             "curl -O ...\n"
             "# 3. Configure\n"
             "...\n"
             "```\n\n"
             "### Option 3: Ubuntu/Debian\n"
             "```bash\n"
             "apt-get update\n"
             "apt-get install ...\n"
             "```\n\n"
             "### Option 4: Windows\n"
             "1. Download installer from...\n"
             "2. Run setup.exe\n"
             "3. Follow wizard\n\n"
             "## Configuration\n"
             "### Environment Variables\n"
             "| Variable | Description | Default | Required |\n"
             "|----------|-------------|---------|----------|\n"
             "| DB_HOST | Database host | localhost | Yes |\n\n"
             "Create `.env` file:\n"
             "```bash\n"
             "DB_HOST=localhost\n"
             "DB_PORT=5432\n"
             "```\n\n"
             "### Configuration File\n"
             "Edit `config.yml`:\n"
             "```yaml\n"
             "server:\n"
             "  port: 8080\n"
             "```\n\n"
             "## Verification\n"
             "Verify installation:\n"
             "```bash\n"
             "app --version\n"
             "# Expected: v1.2.3\n\n"
             "app health-check\n"
             "# Expected: All systems operational\n"
             "```\n\n"
             "## Troubleshooting\n"
             "### Issue: Port already in use\n"
             "**Symptoms:** Error: EADDRINUSE\n"
             "**Solution:**\n"
             "```bash\n"
             "lsof -i :8080\n"
             "kill -9 [PID]\n"
             "```\n\n"
             "## Upgrading\n"
             "From version X to Y:\n"
             "```bash\n"
             "backup-script\n"
             "upgrade-command\n"
             "```\n\n"
             "## Uninstallation\n"
             "```bash\n"
             "uninstall-script\n"
             "```\n\n"},

            {"faq",
             "## Documentation Structure:\n\n"
             "# Frequently Asked Questions\n\n"
             "## Quick Answers (Top 5)\n"
             "1. **[Most common question]** - Brief answer with link\n"
             "2. ...\n\n"
             "## Getting Started\n"
             "**Q: How do I create my first project?**\n"
             "A: Follow these steps:\n"
             "1. Navigate to Dashboard\n"
             "2. Click 'New Project'\n"
             "3. Fill in details\n\n"
             "See also: [Getting Started Guide](link)\n\n"
             "## Installation & Setup\n"
             "**Q: What are the system requirements?**\n"
             "A: You need...\n\n"
             "## Usage\n"
             "**Q: How do I [common task]?**\n"
             "A: ...\n\n"
             "## Troubleshooting\n"
             "**Q: I'm getting error 'Connection refused'?**\n"
             "A: This usually means... Try:\n"
             "1. Check server is running\n"
             "2. Verify firewall settings\n\n"
             "## Integration\n"
             "**Q: Can I integrate with [other system]?**\n"
             "A: ...\n\n"
             "## Performance\n"
             "**Q: Why is the system slow?**\n"
             "A: ...\n\n"
             "## Security\n"
             "**Q: How is my data protected?**\n"
             "A: ...\n\n"
             "## Still Need Help?\n"
             "- Check [Documentation](link)\n"
             "- Search [Community Forum](link)\n"
             "- Contact Support: support@example.com\n\n"},

            {"troubleshooting_guide",
             "## Documentation Structure:\n\n"
             "# Troubleshooting Guide\n\n"
             "## Quick Diagnostics\n"
             "Run these commands first:\n"
             "```bash\n"
             "app status\n"
             "app logs --tail 50\n"
             "app doctor\n"
             "```\n\n"
             "## Common Issues\n\n"
             "### Issue: Application Won't Start\n"
             "**Symptoms:**\n"
             "- Error message on startup\n"
             "- Process exits immediately\n"
             "- No response on expected port\n\n"
             "**Possible Causes:**\n"
             "1. Port already in use\n"
             "2. Missing dependencies\n"
             "3. Configuration error\n\n"
             "**Solutions:**\n"
             "**Solution 1: Check port availability**\n"
             "```bash\n"
             "netstat -an | grep 8080\n"
             "```\n"
             "If port is used, change in config or kill process.\n\n"
             "**Solution 2: Verify dependencies**\n"
             "```bash\n"
             "app check-deps\n"
             "```\n"
             "Install any missing dependencies.\n\n"
             "**Prevention:**\n"
             "- Use Docker for consistent environment\n"
             "- Run pre-flight checks\n\n"
             "## Installation Issues\n"
             "### Issue: [Name]\n"
             "...\n\n"
             "## Runtime Errors\n"
             "### Issue: [Name]\n"
             "...\n\n"
             "## Performance Problems\n"
             "### Issue: Slow Response Times\n"
             "...\n\n"
             "## Error Reference\n"
             "| Code | Message | Meaning | Solution | Docs |\n"
             "|------|---------|---------|----------|------|\n"
             "| E001 | Connection timeout | Cannot reach server | Check network | [link] |\n\n"
             "## Advanced Debugging\n"
             "### Enabling Debug Mode\n"
             "```bash\n"
             "export DEBUG=*\n"
             "app start\n"
             "```\n\n"
             "### Log Files\n"
             "- **Location:** `/var/log/app/`\n"
             "- **Application log:** `app.log`\n"
             "- **Error log:** `error.log`\n\n"
             "**What to look for:**\n"
             "- ERROR or FATAL entries\n"
             "- Stack traces\n"
             "- Connection timeouts\n\n"
             "## Getting Support\n"
             "### How to Report a Bug\n"
             "Use this template:\n"
             "```\n"
             "**Environment:**\n"
             "- OS: \n"
             "- Version: \n\n"
             "**Steps to Reproduce:**\n"
             "1. \n\n"
             "**Expected:** \n"
             "**Actual:** \n\n"
             "**Logs:**\n"
             "```\n\n"
             "**Contact:**\n"
             "- Community Forum: [link]\n"
             "- GitHub Issues: [link]\n"
             "- Email Support: support@example.com\n\n"}
        };

        auto it = instructions.find(doc_type);
        if (it != instructions.end()) {
            return it->second;
        }

        return "## Instructions:\nCreate comprehensive, well-structured documentation.\n";
    }
};

#endif // PROMPT_TEMPLATES_H
